import type { Block } from "@/components/machine/MachineDoc";
export const aboutBlocks: readonly Block[] = [
  { kind: "p", text: "We build continuity between sessions, starting with adolescent therapists, where it matters most, and expanding across behavioral health. Patients get a private place to talk through the week. Clinicians get the context to make fifty minutes count." },
  { kind: "h2", text: "What we believe" },
  { kind: "p", text: "Therapy works. Context makes it work better." },
  { kind: "p", text: "A session is fifty minutes. A week is 10,080. The work goes deeper when the clinician can see more of it." },
  { kind: "p", text: "Privacy is the product." },
  { kind: "p", text: "Patients choose what they share. Refleo brings forward the keywords the clinician set, surfaces recurring themes, and never counsels." },
  { kind: "p", text: "Built with clinicians, not just for them." },
  { kind: "p", text: "More than a hundred clinician conversations across 8 states have shaped every screen. We keep asking." },
  { kind: "h2", text: "Team" },
  { kind: "p", text: "Vishwas Vijayan · Co-Founder · Rice University · Finance / BBA" },
  { kind: "p", text: "Finance/BBA @ Rice building the commercial and go-to-market side of Refleo" },
  { kind: "p", text: "Junior Associate at a $55M Houston VC fund; AI analyst at AfterQuery (YC W'25)" },
  { kind: "link", label: "Vishwas Vijayan on LinkedIn", href: "https://www.linkedin.com/in/vishwasvijayan/" },
  { kind: "p", text: "Rishi Anarkat · Co-Founder · Rice University · AI / Entrepreneurship" },
  { kind: "p", text: "AI/Entrepreneurship @ Rice architecting Refleo's voice journaling and clinical continuity platform" },
  { kind: "p", text: "Healthcare and AI/ML researcher at M.D. Anderson, Baylor College of Medicine, and McGovern School of Medicine" },
  { kind: "link", label: "Rishi Anarkat on LinkedIn", href: "https://www.linkedin.com/in/rishianarkat/" },
  { kind: "h2", text: "Why it matters" },
  { kind: "p", text: "60M Americans in treatment" },
  { kind: "p", text: "Every one of them has a therapist entering a session with incomplete information." },
  { kind: "p", text: "Refleo fixes that." },
];
