import type { Block } from "@/components/machine/MachineDoc";
export const pricingBlocks: readonly Block[] = [
  { kind: "p", text: "Refleo is built for clinicians who want continuity between sessions. One plan, one price, and for our launch, two months free before you pay anything." },
  { kind: "h2", text: "The plan" },
  { kind: "p", text: "$100 / month" },
  { kind: "p", text: "Per clinician, billed monthly in U.S. dollars, exclusive of taxes." },
  ...["HIPAA · BAA included", "Parental consent built in", "Free for your clients", "iPhone and web"].map((text): Block => ({ kind: "p", text })),
  { kind: "h2", text: "Launch offer" },
  { kind: "p", text: "Your first two months are free. No credit card required." },
  { kind: "p", text: "For our launch, new accounts get their first two months completely free, with no credit card required. The two months begin the day the account is activated, and the offer is available once per clinician and once per practice. This is a launch promotion and may end for new sign-ups." },
  { kind: "p", text: "You will not be charged at the end of your trial, and it does not convert automatically into a paid subscription. Your access continues only if you affirmatively choose a paid plan and add a payment method. We'll send a reminder to your account email at least seven days before your trial ends, describing your options and the then-current price." },
  { kind: "h2", text: "What's included" },
  { kind: "p", text: "Your patients record short voice or text entries between appointments. Refleo organizes those entries, identifies recurring themes, and highlights the words and topics you've chosen to track. The result is a brief summary, always presented alongside the underlying entries, for you to review before the next session." },
  { kind: "h2", text: "Billing details" },
  { kind: "p", text: "Fees are stated in U.S. dollars and are exclusive of taxes." },
  { kind: "p", text: "Refunds. Fees already paid are non-refundable, except where required by applicable law or where we state otherwise in writing." },
  { kind: "p", text: "Non-payment. If a payment is more than fifteen (15) days past due, we may suspend access after notice and an opportunity to cure." },
  { kind: "h2", text: "FAQ" },
  { kind: "p", text: "Who pays for Refleo? Clinicians do. Clients never pay." },
  { kind: "p", text: "What does the free trial include? Everything. As a launch promotion, your first two months are completely free, with no credit card required. To keep using Refleo after that, you add a card and your plan starts at $100 a month. Nothing is charged automatically." },
  { kind: "p", text: "Is Refleo HIPAA compliant? Refleo is a HIPAA business associate. Every clinician signs our Business Associate Agreement at sign-up, and the full agreement is published on this site." },
  { kind: "p", text: "Can I use it with clients under 18? Yes. A parent or guardian signs a Parental Consent and Authorization before a minor's account can be used, and the minor sees a plain-language acknowledgment of their own." },
  { kind: "p", text: "What do my clients see? A simple check-in: voice or text, whenever they want between sessions. They do not see your brief or your notes." },
  { kind: "p", text: "Can I cancel? Any time from Settings. You will not be charged again, and you keep access through the end of the month you have already paid for. The current month is not refunded." },
  { kind: "link", label: "Start free trial", href: "https://app.refleohealth.com/?choose=1" },
];
